# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-22.04
  apt_packages:
    - libmagic1
  tools:
    python: "3.9"
  jobs:
    post_checkout:
      - git fetch --tags || true

# Build documentation in the doc/ directory with Sphinx
sphinx:
   configuration: doc/conf.py

# Additional formats for download
formats: all

# Requirements required to build your docs
python:
   install:
   - requirements: requirements-docs.txt
